# Generated by Django 3.0.2 on 2020-02-25 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category_Details',
            fields=[
                ('category_id', models.IntegerField(max_length=2, primary_key=True, serialize=False)),
                ('category_description', models.CharField(max_length=20)),
            ],
        ),
    ]
