# Generated by Django 3.0.2 on 2020-02-25 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantManagementSystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category_details',
            name='category_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Fooditems_Details',
            fields=[
                ('fooditem_id', models.IntegerField(primary_key=True, serialize=False)),
                ('fooditem_name', models.CharField(max_length=30)),
                ('fooditem_description', models.TextField(max_length=300)),
                ('fooditem_price', models.FloatField(max_length=6)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RestaurantManagementSystem.Category_Details')),
            ],
        ),
    ]
