# Generated by Django 3.0.2 on 2020-02-25 13:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantManagementSystem', '0002_auto_20200225_1818'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items_Master',
            fields=[
                ('item_id', models.IntegerField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='fooditems_details',
            name='fooditem_photo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='static/'),
            preserve_default=False,
        ),
    ]
