# Generated by Django 3.0.2 on 2020-02-25 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantManagementSystem', '0003_auto_20200225_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_Information',
            fields=[
                ('customer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=20)),
                ('customer_address', models.TextField(max_length=200)),
                ('customer_city', models.CharField(max_length=20)),
                ('customer_pincode', models.IntegerField(max_length=6)),
                ('customer_mobileno', models.IntegerField(max_length=10)),
                ('customer_emailid', models.CharField(max_length=25)),
            ],
        ),
        migrations.RemoveField(
            model_name='fooditems_details',
            name='fooditem_photo',
        ),
    ]
