# Generated by Django 3.0.2 on 2020-02-25 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantManagementSystem', '0004_auto_20200225_1938'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_Details',
            fields=[
                ('emp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('emp_name', models.CharField(max_length=20)),
                ('emp_address', models.TextField(max_length=200)),
                ('emp_city', models.CharField(max_length=20)),
                ('emp_state', models.CharField(max_length=20)),
                ('emp_pincode', models.IntegerField()),
                ('emp_mobileno', models.IntegerField()),
                ('emp_emailid', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Order_Details',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('order_date', models.DateTimeField(verbose_name='date published')),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RestaurantManagementSystem.Employee_Details')),
            ],
        ),
        migrations.CreateModel(
            name='Order_Items',
            fields=[
                ('orderitem_id', models.IntegerField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('fooditem_price', models.FloatField()),
                ('amount', models.FloatField()),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RestaurantManagementSystem.Order_Details')),
            ],
        ),
        migrations.CreateModel(
            name='Salesbill',
            fields=[
                ('salesbill_no', models.IntegerField(primary_key=True, serialize=False)),
                ('salesbill_date', models.DateTimeField(verbose_name='date published')),
                ('order_amount', models.FloatField()),
                ('tax', models.FloatField()),
                ('discount', models.FloatField()),
                ('net_amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Table_Master',
            fields=[
                ('table_id', models.IntegerField(primary_key=True, serialize=False)),
                ('table_capacity', models.IntegerField()),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RestaurantManagementSystem.Employee_Details')),
            ],
        ),
        migrations.DeleteModel(
            name='Items_Master',
        ),
        migrations.AddField(
            model_name='customer_information',
            name='customer_state',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customer_information',
            name='customer_mobileno',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='customer_information',
            name='customer_pincode',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='salesbill',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RestaurantManagementSystem.Customer_Information'),
        ),
        migrations.AddField(
            model_name='salesbill',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RestaurantManagementSystem.Order_Details'),
        ),
        migrations.AddField(
            model_name='order_details',
            name='table_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RestaurantManagementSystem.Table_Master'),
        ),
    ]
