# Generated by Django 3.0.2 on 2020-03-12 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantManagementSystem', '0005_auto_20200226_0042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table_master',
            name='emp_id',
        ),
        migrations.AddField(
            model_name='customer_information',
            name='customer_total',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='table_master',
            name='customer_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='RestaurantManagementSystem.Customer_Information'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='table_master',
            name='table_occupied',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
