# Generated by Django 3.0.2 on 2020-03-13 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantManagementSystem', '0008_auto_20200312_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditems_details',
            name='fooditem_photo',
            field=models.ImageField(null=True, upload_to='items'),
        ),
        migrations.AlterField(
            model_name='fooditems_details',
            name='fooditem_id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
