# Generated by Django 3.0.2 on 2020-03-17 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantManagementSystem', '0011_remove_order_details_table_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_information',
            name='table_id',
            field=models.IntegerField(null=True),
        ),
    ]
