# Generated by Django 3.0.2 on 2020-03-17 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantManagementSystem', '0012_customer_information_table_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_information',
            name='table_id',
            field=models.IntegerField(default=0),
        ),
    ]
