# Generated by Django 3.0.2 on 2020-03-17 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantManagementSystem', '0015_remove_order_details_table_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_details',
            name='table_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='RestaurantManagementSystem.Customer_Information'),
            preserve_default=False,
        ),
    ]
