# Generated by Django 3.0.2 on 2020-03-17 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantManagementSystem', '0016_order_details_table_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_details',
            name='table_id',
        ),
    ]
